group = 'com.sparkjava'
version = System.properties.getProperty('version', '0.0.0') + "-SNAPSHOT"

buildscript {
    ext.jettyVersion = '12.0.17'
    ext.mockitoVersion = '5.16.0'
    ext.slf4jVersion = '2.0.17'
    ext.junitVersion = '5.12.0'
    repositories {
        mavenCentral()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
}
apply plugin: 'java'

repositories {
    mavenCentral()
}


dependencies {
    implementation "org.slf4j:slf4j-api:$slf4jVersion"
    implementation "org.slf4j:slf4j-simple:$slf4jVersion"
    testImplementation "org.slf4j:slf4j-api:$slf4jVersion"
    testImplementation "org.slf4j:slf4j-simple:$slf4jVersion"

    implementation "org.eclipse.jetty:jetty-server:$jettyVersion"
    implementation "org.eclipse.jetty.ee9:jetty-ee9-webapp:$jettyVersion"
    implementation "org.eclipse.jetty.ee9.websocket:jetty-ee9-websocket-jetty-server:$jettyVersion"// https://mvnrepository.com/artifact/org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-jakarta-server
    implementation "org.eclipse.jetty.ee9.websocket:jetty-ee9-websocket-jakarta-server:$jettyVersion"
    implementation "jakarta.websocket:jakarta.websocket-api:2.0.0"

    implementation "org.eclipse.jetty.websocket:jetty-websocket-jetty-api:$jettyVersion"
    implementation "org.eclipse.jetty.websocket:jetty-websocket-jetty-server:$jettyVersion"
    // https://mvnrepository.com/artifact/org.eclipse.jetty.ee9.websocket/jetty-ee9-websocket-jetty-api
    implementation "org.eclipse.jetty.websocket:jetty-websocket-core-server:$jettyVersion"

    //testImplementation "net.bytebuddy:byte-buddy-agent:1.14.5"
    //testImplementation "net.bytebuddy:byte-buddy:1.14.5"
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "org.mockito:mockito-junit-jupiter:$mockitoVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.12.0"

    testImplementation 'org.hamcrest:hamcrest:3.0'
    testImplementation 'org.apache.commons:commons-lang3:3.17.0'

    testImplementation "org.apache.httpcomponents.client5:httpclient5:5.4.2"
    testImplementation "org.freemarker:freemarker:2.3.34"
    testImplementation "com.google.code.gson:gson:2.12.1"
    testImplementation "org.eclipse.jetty.ee9.websocket:jetty-ee9-websocket-jetty-client:$jettyVersion"
    implementation 'org.jetbrains:annotations:26.0.2'

}

test {

//    useJUnitJupiter()

    forkEvery = 1
    maxParallelForks = 1
    useJUnitPlatform()
    failFast = true
    reports {

    }
    //jvmArgs['-Djavaagent=byte-buddy-agent.jar']
    //jvmArgs['--add-modules java.se --add-exports java.base/jdk.internal.ref=EVERYONE --add-opens java.base/java.lang=EVERYONE --add-opens java.base/java.nio=EVERYONE --add-opens java.base/sun.nio.ch=EVERYONE --add-opens java.management/sun.management=EVERYONE --add-opens jdk.management/com.sun.management.internal=EVERYONE --add-opens java.base/java.lang.reflect=test']

}
